name: scrape_and_deploy

on:
    workflow_dispatch: 
      inputs:
        bootstrap:
          description: 'Run with --bootstrap?'
          required: true
          type: boolean
          default: false
    schedule:
      - cron: '0 0 * * *' # Runs at midnight every day

jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Scrape
          run: |
            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && "${{ github.event.inputs.bootstrap }}"; then
              ./scrape.sh --bootstrap
            else
              ./scrape.sh
            fi
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Add scraped CSV files'
            add: '*.csv --force'
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Update sqlite db'
            add: '*.db --force'
        - name: Install Vercel
          run: npm install -g vercel 
        - name: Deploy Datasette using Vercel
          env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          run: |-
            datasette publish vercel itaipu.db \
              --token $VERCEL_TOKEN \
              --project itaipu \
              --vercel-json vercel.json

