name: scrape_and_deploy

on:
    workflow_dispatch: 
      inputs:
        bootstrap:
          description: 'Run with --bootstrap?'
          required: true
          type: boolean
          default: false
    schedule:
      - cron: '0 0 * * *' # Runs at midnight every day

jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Scrape
          run: |
            if [ "${{ github.event_name }}" = "workflow_dispatch" ] && "${{ github.event.inputs.bootstrap }}"; then
              ./scrape.sh --bootstrap
            else
              ./scrape.sh
            fi
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Add scraped CSV files'
            add: 'data/*.csv --force'
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Update sqlite db'
            add: '*.db --force'
        - name: Set up SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

        - name: Deploy database to droplet
          run: |
            rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
              itaipu.db \
              ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/opt/itaipu/data/itaipu.db

        - name: Restart Datasette
          run: |
            ssh -i ~/.ssh/deploy_key \
              ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
              "sudo systemctl restart datasette"

