name: scrape_yacyreta

on:
    workflow_dispatch:
    schedule:
      - cron: '0 1 * * *' # 01:00 UTC (1h offset from itaipu)

jobs:
    scrape:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Install Python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Scrape
          run: ./scrape.sh yacyreta
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Add scraped yacyreta CSV files'
            add: 'data/yacyreta/*.csv --force'
        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            default_author: github_actions
            message: 'Update yacyreta sqlite db'
            add: 'yacyreta.db --force'
        - name: Set up SSH
          env:
            SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

        - name: Deploy yacyreta database to droplet
          run: |
            rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
              yacyreta.db \
              ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/opt/itaipu/data/yacyreta.db

        - name: Restart Datasette
          run: |
            ssh -i ~/.ssh/deploy_key \
              ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} \
              "sudo systemctl restart datasette"
